routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('biome/json', 'BiomeController@json')->name('biome.json');
    Route::resource('biome', 'BiomeController');
    Route::get('charge/json', 'ChargeController@json')->name('charge.json');
    Route::post('charge/search', 'ChargeController@search')->name('charge.search');
    Route::resource('charge', 'ChargeController');
    Route::get('domain/json', 'DomainController@json')->name('domain.json');
    Route::resource('domain', 'DomainController');
    Route::get('mineral/json', 'MineralController@json')->name('mineral.json');
    Route::resource('mineral', 'MineralController');
    Route::get('pattern/json', 'PatternController@json')->name('pattern.json');
    Route::post('pattern/search', 'PatternController@search')->name('pattern.search');
    Route::resource('pattern', 'PatternController');
    Route::get('profession/json', 'ProfessionController@json')->name('profession.json');
    Route::resource('profession', 'ProfessionController');
    Route::get('resource/json', 'ResourceController@json')->name('resource.json');
    Route::post('resource/search', 'ResourceController@search')->name('resource.search');
    Route::resource('resource', 'ResourceController');
    Route::get('species/json', 'SpeciesController@json')->name('species.json');
    Route::get('species/quick', 'SpeciesController@quick')->name('species.quick');
    Route::post('species/search', 'SpeciesController@search')->name('species.search');
    Route::resource('species', 'SpeciesController');

    // Pattern routes
    Route::get('pattern/{pattern}/slot/create', 'PatternController@createSlot')->name('pattern.create_slot');
    Route::get('pattern/{pattern}/slot/{slot}/edit', 'PatternController@editSlot')->name('pattern.edit_slot');
    Route::post('pattern/{pattern}/slot', 'PatternController@storeSlot')->name('pattern.store_slot');
    Route::put('pattern/{pattern}/slot/{slot}', 'PatternController@updateSlot')->name('pattern.update_slot');

    // Species routes
    Route::get('species/{species}/resource/create', 'SpeciesController@createResource')->name('species.create_resource');
    Route::get('species/{species}/resource/{resource}/edit', 'SpeciesController@editResource')->name('species.edit_resource');
    Route::post('species/{species}/resource', 'SpeciesController@storeResource')->name('species.store_resource');
    Route::put('species/{species}/resource/{resource}', 'SpeciesController@updateResource')->name('species.update_resource');

    Route::get('species/{species}/age_category/create', 'SpeciesController@createAgeCategory')->name('species.create_age_category');
    Route::get('species/{species}/age_category/{age_category}/edit', 'SpeciesController@editAgeCategory')->name('species.edit_age_category');
    Route::post('species/{species}/age_category', 'SpeciesController@storeAgeCategory')->name('species.store_age_category');
    Route::put('species/{species}/age_category/{age_category}', 'SpeciesController@updateAgeCategory')->name('species.update_age_category');

    Route::get('species/{species}/trait_template/create', 'SpeciesController@createTraitTemplate')->name('species.create_trait_template');
    Route::get('species/{species}/trait_template/{trait_template}/edit', 'SpeciesController@editTraitTemplate')->name('species.edit_trait_template');
    Route::post('species/{species}/trait_template', 'SpeciesController@storeTraitTemplate')->name('species.store_trait_template');
    Route::put('species/{species}/trait_template/{trait_template}', 'SpeciesController@updateTraitTemplate')->name('species.update_trait_template');

    Route::post('quick/race', 'SpeciesController@storeQuickRace')->name('quick.race');

    // Mineral routes
    Route::get('mineral/{mineral}/resource/create', 'MineralController@createResource')->name('mineral.create_resource');
    Route::get('mineral/{mineral}/resource/{resource}/edit', 'MineralController@editResource')->name('mineral.edit_resource');
    Route::post('mineral/{mineral}/resource', 'MineralController@storeResource')->name('mineral.store_resource');
    Route::put('mineral/{mineral}/resource/{resource}', 'MineralController@updateResource')->name('mineral.update_resource');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'HomeController@index')->name('dashboard');

app/Http/Controllers/SpeciesController.php
<?php

namespace App\Http\Controllers;

use App\Models\AgeCategory;
use App\Models\Resource;
use App\Models\Species;
use App\Models\Tag;
use App\Models\TraitTemplate;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class SpeciesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index(Request $request)
    {
        if (!empty($request->query('tag'))) {
            $tag = Tag::where('name', '=', $request->query('tag'))->first();
            if (empty($tag)) {
                $species = [];
            } else {
                $species = $tag->species()->orderBy('name')->get();
            }
        } else {
            $species = Species::orderBy('name')->paginate(15);
        }

        return view('species.index', ['species' => $species]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create()
    {
        return view('species.create');
    }

    public function json()
    {
        return view('species.json');
    }

    public function quick()
    {
        return view('species.quick');
    }

    public function search(Request $request)
    {
        $name = $request->input('name');

        $species = Species::where('name', 'like', "%$name%")->orderBy('name')->paginate(15);

        return view('species.index', ['species' => $species]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $species = new Species;

        $this->save($species, $request);

        return redirect()->route('species.show', ['species' => $species]);
    }

    /**
     * Display the specified resource.
     *
     * @param Species $species
     *
     * @return Renderable
     */
    public function show(Species $species)
    {
        return view('species.show', ['species' => $species]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Species $species
     *
     * @return Renderable
     */
    public function edit(Species $species)
    {
        $tags = convert_tags_to_string($species);

        return view('species.edit', ['species' => $species, 'tags' => $tags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Species $species
     *
     * @return RedirectResponse
     */
    public function update(Request $request, Species $species)
    {
        $this->save($species, $request);

        return redirect()->route('species.show', ['species' => $species]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Species $species
     *
     * @return Response
     */
    public function destroy(Species $species)
    {
        //
    }

    public function save(Species $species, Request $request)
    {
        $input = $request->all();

        $species->name = $input['name'];
        $species->plural_name = $input['plural_name'];
        $species->adjective = $input['adjective'];
        $species->commonality = $input['commonality'];
        $species->humidity_min = $input['humidity_min'];
        $species->humidity_max = $input['humidity_max'];
        $species->temperature_min = $input['temperature_min'];
        $species->temperature_max = $input['temperature_max'];

        $species->save();

        update_tags($species, $input['tags']);
    }

    // Shortcut functions

    public function storeQuickRace(Request $request)
    {
        $species = new Species;
        $input = $request->all();

        if (empty($input['name'])) {
            return response('error: name must be set', 500);
        }

        $species->name = $input['name'];
        $species->plural_name = $species->name . 's';
        $species->adjective = $species->name;
        $species->commonality = 100;
        $species->humidity_min = 0;
        $species->humidity_max = 0;
        $species->temperature_min = 0;
        $species->temperature_max = 0;

        $species->save();

        update_tags($species, $species->name . ',sentient,race');

        $infant = new AgeCategory;
        $infant->name = 'infant';
        $infant->age_min = 0;
        $infant->age_max = 1;
        $infant->height_base_female = 18;
        $infant->height_base_male = 18;
        $infant->height_range_dice = '2d8';
        $infant->weight_base_female = 5;
        $infant->weight_base_male = 5;
        $infant->weight_range_dice = '2d10';
        $infant->size_category = 'tiny';
        $infant->commonality = 1;

        $child = new AgeCategory;
        $child->name = 'child';
        $child->age_min = 2;
        $child->age_max = 12;
        $child->height_base_female = 42;
        $child->height_base_male = 42;
        $child->height_range_dice = '2d8';
        $child->weight_base_female = 36;
        $child->weight_base_male = 36;
        $child->weight_range_dice = '2d10';
        $child->size_category = 'small';
        $child->commonality = 10;

        $teenager = new AgeCategory;
        $teenager->name = 'teenager';
        $teenager->age_min = 13;
        $teenager->age_max = 19;
        $teenager->height_base_female = 57;
        $teenager->height_base_male = 62;
        $teenager->height_range_dice = '2d8';
        $teenager->weight_base_female = 89;
        $teenager->weight_base_male = 92;
        $teenager->weight_range_dice = '2d10';
        $teenager->size_category = 'medium';
        $teenager->commonality = 30;

        $youngAdult = new AgeCategory;
        $youngAdult->name = 'young adult';
        $youngAdult->age_min = 20;
        $youngAdult->age_max = 25;
        $youngAdult->height_base_female = 57;
        $youngAdult->height_base_male = 62;
        $youngAdult->height_range_dice = '2d8';
        $youngAdult->weight_base_female = 105;
        $youngAdult->weight_base_male = 140;
        $youngAdult->weight_range_dice = '2d10';
        $youngAdult->size_category = 'medium';
        $youngAdult->commonality = 100;

        $adult = new AgeCategory;
        $adult->name = 'adult';
        $adult->age_min = 26;
        $adult->age_max = 69;
        $adult->height_base_female = 57;
        $adult->height_base_male = 62;
        $adult->height_range_dice = '2d8';
        $adult->weight_base_female = 105;
        $adult->weight_base_male = 140;
        $adult->weight_range_dice = '2d10';
        $adult->size_category = 'medium';
        $adult->commonality = 150;

        $elderly = new AgeCategory;
        $elderly->name = 'elderly';
        $elderly->age_min = 70;
        $elderly->age_max = 100;
        $elderly->height_base_female = 57;
        $elderly->height_base_male = 62;
        $elderly->height_range_dice = '2d8';
        $elderly->weight_base_female = 105;
        $elderly->weight_base_male = 140;
        $elderly->weight_range_dice = '2d10';
        $elderly->size_category = 'medium';
        $elderly->commonality = 150;

        $species->ageCategories()->saveMany([$infant, $child, $teenager, $youngAdult, $adult, $elderly]);

        return response()->json($species);
    }

    // Resource functions

    public function createResource(Species $species)
    {
        return view('resource.create-for', ['item' => $species, 'itemType' => 'species']);
    }

    public function editResource(Species $species, Resource $resource)
    {
        $tags = convert_tags_to_string($resource);

        return view('resource.edit-for', ['item' => $species, 'itemType' => 'species', 'resource' => $resource, 'tags' => $tags]);
    }

    public function updateResource(Species $species, Resource $resource, Request $request)
    {
        $rc = new ResourceController();
        $rc->saveFor($species, $resource, $request);

        return redirect()->route('species.show', ['species' => $species]);
    }

    public function storeResource(Species $species, Request $request)
    {
        $resource = new Resource;

        $rc = new ResourceController();
        $rc->saveFor($species, $resource, $request);

        return redirect()->route('species.show', ['species' => $species]);
    }

    // Age Category functions

    public function createAgeCategory(Species $species)
    {
        return view('species.age_category.create', ['species' => $species]);
    }

    public function editAgeCategory(Species $species, AgeCategory $ageCategory)
    {
        return view('species.age_category.edit', ['species' => $species, 'ageCategory' => $ageCategory]);
    }

    public function updateAgeCategory(Species $species, AgeCategory $ageCategory, Request $request)
    {
        $this->saveAgeCategory($species, $ageCategory, $request);

        return redirect()->route('species.show', ['species' => $species]);
    }

    public function storeAgeCategory(Species $species, Request $request)
    {
        $ageCategory = new AgeCategory;

        $this->saveAgeCategory($species, $ageCategory, $request);

        return redirect()->route('species.show', ['species' => $species]);
    }

    public function saveAgeCategory(Species $species, AgeCategory $ageCategory, Request $request)
    {
        $input = $request->all();

        $ageCategory->name = $input['name'];
        $ageCategory->age_min = $input['age_min'];
        $ageCategory->age_max = $input['age_max'];
        $ageCategory->size_category = $input['size_category'];
        $ageCategory->height_base_female = $input['height_base_female'];
        $ageCategory->height_base_male = $input['height_base_male'];
        $ageCategory->height_range_dice = $input['height_range_dice'];
        $ageCategory->weight_base_female = $input['weight_base_female'];
        $ageCategory->weight_base_male = $input['weight_base_male'];

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/species/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Species
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="species-creation-form" method="POST" action="{{ route('species.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="plural_name">Plural Name</label>
                <input type="text" id="plural_name" name="plural_name" class="form-control">
            </div>
            <div class="form-group">
                <label for="adjective">Adjective</label>
                <input type="text" id="adjective" name="adjective" class="form-control">
            </div>
            <div class="form-group">
                <label for="humidity_min">Min Humidity</label>
                <input id="humidity_min" name="humidity_min" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label for="humidity_max">Max Humidity</label>
                <input id="humidity_max" name="humidity_max" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label for="temperature_min">Min Temperature</label>
                <input id="temperature_min" name="temperature_min" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label for="temperature_max">Max Temperature</label>
                <input id="temperature_max" name="temperature_max" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label for="commonality">Commonality</label>
                <input id="commonality" name="commonality" type="number" class="form-control">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/species/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Species "{{ $species->name }}"
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="species-edit-form" method="POST"
              action="{{ route('species.update', ['species' => $species]) }}">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ $species->name }}">
            </div>
            <div class="form-group">
                <label for="plural_name">Plural Name</label>
                <input type="text" id="plural_name" name="plural_name" class="form-control"
                       value="{{ $species->plural_name }}">
            </div>
            <div class="form-group">
                <label for="adjective">Adjective</label>
                <input type="text" id="adjective" name="adjective" class="form-control"
                       value="{{ $species->adjective }}">
            </div>
            <div class="form-group">
                <label for="humidity_min">Min Humidity</label>
                <input id="humidity_min" name="humidity_min" type="number" class="form-control"
                       value="{{ $species->humidity_min }}">
            </div>
            <div class="form-group">
                <label for="humidity_max">Max Humidity</label>
                <input id="humidity_max" name="humidity_max" type="number" class="form-control"
                       value="{{ $species->humidity_max }}">
            </div>
            <div class="form-group">
                <label for="temperature_min">Min Temperature</label>
                <input id="temperature_min" name="temperature_min" type="number" class="form-control"
                       value="{{ $species->temperature_min }}">
            </div>
            <div class="form-group">
                <label for="temperature_max">Max Temperature</label>
                <input id="temperature_max" name="temperature_max" type="number" class="form-control"
                       value="{{ $species->temperature_max }}">
            </div>
            <div class="form-group">
                <label for="commonality">Commonality</label>
                <input id="commonality" name="commonality" type="number" class="form-control"
                       value="{{ $species->commonality }}">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control" value="{{ $tags }}">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>

        <h2>Age Categories</h2>

        <a href="{{ route('species.create_age_category', ['species' => $species]) }}" class="btn">Add</a>

        <ul>
            @foreach($species->ageCategories as $ageCategory)
                <li>
                    <a class="text-green-700 underline hover:no-underline"
                       href="{{ route('species.edit_age_category', ['species' => $species, 'age_category' => $ageCategory]) }}">{{ $ageCategory->name }}</a>
                </li>
            @endforeach
        </ul>

        <h2>Trait Templates</h2>

        <a href="{{ route('species.create_trait_template', ['species' => $species]) }}" class="btn">Add</a>

        <ul>
            @foreach($species->traitTemplates as $traitTemplate)
                <li>
                    <a class="text-green-700 underline hover:no-underline"
                       href="{{ route('species.edit_trait_template', ['species' => $species, 'trait_template' => $traitTemplate]) }}">{{ $traitTemplate->name }}</a>
                </li>
            @endforeach
        </ul>

        <h2>Resources</h2>

        <a href="{{ route('species.create_resource', ['species' => $species]) }}"
           class="btn">Add</a>

        @if(sizeof($species->resources) > 0)
            <table>
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Main Material</th>
                    <th>Origin</th>
                    <th>Tags</th>
                </tr>
                </thead>
                <tbody>
                @foreach($species->resources as $resource)
                    <tr>
                        <td><a class="text-green-700 underline hover:no-underline" href="{{ route('species.edit_resource', ['species' => $species, 'resource' => $resource]) }}">{{ $resource->name }}</a></td>
                        <td>{{ $resource->description }}</td>
                        <td>{{ $resource->main_material }}</td>
                        <td>{{ $resource->origin }}</td>
                        <td>@foreach($resource->tags as $tag)<span class="tag">{{$tag->name}}</span> @endforeach</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif
    </div>
</x-app-layout>

resources/views/species/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Species
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif
        @if (Auth::user()->is_admin)
            <p class="flex">
                <a href="{{ route('species.create') }}" class="btn">Create New</a>
                <a href="{{ route('species.json') }}" class="btn">Create from JSON</a>
                <a href="{{ route('species.quick') }}" class="btn">Create Quick Race</a>
            </p>
        @endif

        <form method="POST" action="{{ route('species.search') }}">
            @csrf
            <div class="shadow flex m-4 items-center p-3">
                <h3 class="block mx-2 font-bold">Search</h3>
                <input type="text" name="name" class="border-3 border-gray-600 p-2"
                       placeholder="name to search for">
                <button type="submit" class="btn">Search</button>
            </div>
        </form>

        <h2>List of Species</h2>

        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Tags</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($species as $spe)
                <tr>
                    <td><a class="text-green-700 underline hover:no-underline" href="{{ route('species.show', ['species'=>$spe->id]) }}">{{ $spe->name }}</a></td>
                    <td>@foreach($spe->tags as $tag)<span class="tag">{{ $tag->name }}</span> @endforeach</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $species->links() }}
    </div>
</x-app-layout>

resources/views/species/json.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Species from JSON
        </h2>
    </x-slot>
    <div id="app">
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <p>@{{ message }}</p>

        <p>The JSON must have a parent entity "species" that contains an array of properly-formatted pattern.</p>

        <input type="hidden" ref="jsonType" value="species">

        <div class="form-group">
            <label for="json-data">JSON</label>
            <textarea class="form-control" id="json-data" rows="12" v-model="jsonData"></textarea>
        </div>

        <button class="btn" id="create-from-json" v-on:click="createFromJson" :disabled="!jsonData">
            Process
        </button>
        @if (Auth::user())
            <input type="hidden" ref="apiToken" value="{{ Auth::user()->api_token }}">
        @endif
    </div>

    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</x-app-layout>

resources/views/species/quick.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Quick Race
        </h2>
    </x-slot>

    <div id="app">
        <div class="form-group">
            <label for="quick-species">Species Name</label>
            <input type="text" id="quick-species" name="quick-species" class="form-control" placeholder="species name"
                   v-model="quickSpecies">
            <button class="btn" id="create-quick-race" v-on:click="createQuickRace">Create
                Race
            </button>
        </div>

        <p>@{{ message }}</p>

        @if (Auth::user())
            <input type="hidden" ref="apiToken" value="{{ Auth::user()->api_token }}">
        @endif
    </div>

    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</x-app-layout>

resources/views/species/search.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Species Search
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form method="POST" action="{{ route('species.search') }}">
            @csrf
            <div class="shadow flex m-4 items-center p-3">
                <h3 class="block mx-2 font-bold">Search</h3>
                <input type="text" name="name" class="border-3 border-gray-600 p-2"
                       placeholder="name to search for">
                <button type="submit" class="btn">Search</button>
            </div>
        </form>

        <h2>Search Results</h2>

        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Tags</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($species as $spe)
                <tr>
                    <td><a class="text-green-700 underline hover:no-underline" href="{{ route('species.show', ['species'=>$spe->id]) }}">{{ $spe->name }}</a></td>
                    <td>@foreach($spe->tags as $tag)<span class="tag">{{ $tag->name }}</span> @endforeach</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $species->links() }}
    </div>
</x-app-layout>