routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('biome/json', 'BiomeController@json')->name('biome.json');
    Route::resource('biome', 'BiomeController');
    Route::get('charge/json', 'ChargeController@json')->name('charge.json');
    Route::post('charge/search', 'ChargeController@search')->name('charge.search');
    Route::resource('charge', 'ChargeController');
    Route::get('domain/json', 'DomainController@json')->name('domain.json');
    Route::resource('domain', 'DomainController');
    Route::get('mineral/json', 'MineralController@json')->name('mineral.json');
    Route::resource('mineral', 'MineralController');
    Route::get('pattern/json', 'PatternController@json')->name('pattern.json');
    Route::post('pattern/search', 'PatternController@search')->name('pattern.search');
    Route::resource('pattern', 'PatternController');
    Route::get('profession/json', 'ProfessionController@json')->name('profession.json');
    Route::resource('profession', 'ProfessionController');
    Route::get('resource/json', 'ResourceController@json')->name('resource.json');
    Route::post('resource/search', 'ResourceController@search')->name('resource.search');
    Route::resource('resource', 'ResourceController');
    Route::get('species/json', 'SpeciesController@json')->name('species.json');
    Route::get('species/quick', 'SpeciesController@quick')->name('species.quick');
    Route::post('species/search', 'SpeciesController@search')->name('species.search');
    Route::resource('species', 'SpeciesController');

    // Pattern routes
    Route::get('pattern/{pattern}/slot/create', 'PatternController@createSlot')->name('pattern.create_slot');
    Route::get('pattern/{pattern}/slot/{slot}/edit', 'PatternController@editSlot')->name('pattern.edit_slot');
    Route::post('pattern/{pattern}/slot', 'PatternController@storeSlot')->name('pattern.store_slot');
    Route::put('pattern/{pattern}/slot/{slot}', 'PatternController@updateSlot')->name('pattern.update_slot');

    // Species routes
    Route::get('species/{species}/resource/create', 'SpeciesController@createResource')->name('species.create_resource');
    Route::get('species/{species}/resource/{resource}/edit', 'SpeciesController@editResource')->name('species.edit_resource');
    Route::post('species/{species}/resource', 'SpeciesController@storeResource')->name('species.store_resource');
    Route::put('species/{species}/resource/{resource}', 'SpeciesController@updateResource')->name('species.update_resource');

    Route::get('species/{species}/age_category/create', 'SpeciesController@createAgeCategory')->name('species.create_age_category');
    Route::get('species/{species}/age_category/{age_category}/edit', 'SpeciesController@editAgeCategory')->name('species.edit_age_category');
    Route::post('species/{species}/age_category', 'SpeciesController@storeAgeCategory')->name('species.store_age_category');
    Route::put('species/{species}/age_category/{age_category}', 'SpeciesController@updateAgeCategory')->name('species.update_age_category');

    Route::get('species/{species}/trait_template/create', 'SpeciesController@createTraitTemplate')->name('species.create_trait_template');
    Route::get('species/{species}/trait_template/{trait_template}/edit', 'SpeciesController@editTraitTemplate')->name('species.edit_trait_template');
    Route::post('species/{species}/trait_template', 'SpeciesController@storeTraitTemplate')->name('species.store_trait_template');
    Route::put('species/{species}/trait_template/{trait_template}', 'SpeciesController@updateTraitTemplate')->name('species.update_trait_template');

    Route::post('quick/race', 'SpeciesController@storeQuickRace')->name('quick.race');

    // Mineral routes
    Route::get('mineral/{mineral}/resource/create', 'MineralController@createResource')->name('mineral.create_resource');
    Route::get('mineral/{mineral}/resource/{resource}/edit', 'MineralController@editResource')->name('mineral.edit_resource');
    Route::post('mineral/{mineral}/resource', 'MineralController@storeResource')->name('mineral.store_resource');
    Route::put('mineral/{mineral}/resource/{resource}', 'MineralController@updateResource')->name('mineral.update_resource');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'HomeController@index')->name('dashboard');

app/Models/Domain.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    protected $fillable = [
        'name',
        'appearance_traits',
        'personality_traits',
        'holy_items',
        'holy_symbols',
    ];

    protected $hidden = [
        'id',
        'created_at',
        'updated_at',
    ];
}

app/Http/Controllers/DomainController.php
<?php

namespace App\Http\Controllers;

use App\Models\Domain;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class DomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index()
    {
        $domains = Domain::orderBy('name')->paginate(15);

        return view('domain.index', ['domains' => $domains]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create()
    {
        return view('domain.create');
    }

    public function json()
    {
        return view('domain.json');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $domain = new Domain;

        $this->save($domain, $request);

        return redirect()->route('domain.show', ['domain' => $domain]);
    }

    /**
     * Display the specified resource.
     *
     * @param Domain $domain
     *
     * @return Renderable
     */
    public function show(Domain $domain)
    {
        return view('domain.show', ['domain' => $domain]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Domain $domain
     *
     * @return Renderable
     */
    public function edit(Domain $domain)
    {
        return view('domain.edit', ['domain' => $domain]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Domain $domain
     *
     * @return RedirectResponse
     */
    public function update(Request $request, Domain $domain)
    {
        $this->save($domain, $request);

        return redirect()->route('domain.show', ['domain' => $domain]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Domain $domain
     *
     * @return Response
     */
    public function destroy(Domain $domain)
    {
        //
    }

    function save(Domain $domain, Request $request)
    {
        $domain->name = $request->name;
        $domain->appearance_traits = $request->appearance_traits;
        $domain->personality_traits = $request->personality_traits;
        $domain->holy_items = $request->holy_items;
        $domain->holy_symbols = $request->holy_symbols;

        $domain->save();
    }

    public function getJSON()
    {
        $domains = Domain::all()->toJSON();

        $domains = '{"domains":' . $domains . '}';

        return response($domains)->header('Content-Type', 'application/json');
    }

    public function storeFromJson(Request $request)
    {
        $data = json_decode($request->data);

        if (empty($data->domains)) {
            return response('invalid data for domains', '400');
        }

        $newRecordsCount = 0;

        foreach($data->domains as $object) {
            $domain = new Domain;

            $domain->name = $object->name;
            $domain->appearance_traits = $object->appearance_traits;
            $domain->personality_traits = $object->personality_traits;
            $domain->holy_items = $object->holy_items;
            $domain->holy_symbols = $object->holy_symbols;

            $domain->save();

            $newRecordsCount++;
        }

        return response()->json([
            'state' => 'success',
            'new_records_count' => $newRecordsCount,
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/domain/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Domain
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="domain-creation-form" method="POST" action="{{ route('domain.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="appearance_traits">Appearance Traits</label>
                <input type="text" id="appearance_traits" name="appearance_traits" class="form-control">
            </div>
            <div class="form-group">
                <label for="personality_traits">Personality Traits</label>
                <input type="text" id="personality_traits" name="personality_traits" class="form-control">
            </div>
            <div class="form-group">
                <label for="holy_items">Holy Items</label>
                <input type="text" id="holy_items" name="holy_items" class="form-control">
            </div>
            <div class="form-group">
                <label for="holy_symbols">Holy Symbols</label>
                <input type="text" id="holy_symbols" name="holy_symbols" class="form-control">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/domain/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Domain "{{ $domain->name }}"
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="domain-edit-form" method="POST" action="{{ route('domain.update', ['domain' => $domain]) }}">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ $domain->name }}">
            </div>
            <div class="form-group">
                <label for="appearance_traits">Appearance Traits</label>
                <input type="text" id="appearance_traits" name="appearance_traits" class="form-control"
                       value="{{ $domain->appearance_traits }}">
            </div>
            <div class="form-group">
                <label for="personality_traits">Personality Traits</label>
                <input type="text" id="personality_traits" name="personality_traits" class="form-control"
                       value="{{ $domain->personality_traits }}">
            </div>
            <div class="form-group">
                <label for="holy_items">Holy Items</label>
                <input type="text" id="holy_items" name="holy_items" class="form-control"
                       value="{{ $domain->holy_items }}">
            </div>
            <div class="form-group">
                <label for="holy_symbols">Holy Symbols</label>
                <input type="text" id="holy_symbols" name="holy_symbols" class="form-control"
                       value="{{ $domain->holy_symbols }}">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/domain/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Domains
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        @if (Auth::user()->is_admin)
            <p class="flex">
                <a href="{{ route('domain.create') }}" class="btn">Create New</a>
                <a href="{{ route('domain.json') }}" class="btn">Create from JSON</a>
            </p>
        @endif

        <h2>List of Domains</h2>

        <ul>
            @foreach ($domains as $domain)
                <li>
                    <a class="text-green-700 underline hover:no-underline"
                       href="{{ route('domain.show', ['domain' => $domain]) }}">{{ $domain->name }}</a>
                </li>
            @endforeach
        </ul>

        {{ $domains->links() }}
    </div>
</x-app-layout>

resources/views/domain/json.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Domain from JSON
        </h2>
    </x-slot>

    <div id="app">
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <p>@{{ message }}</p>

        <p>The JSON must have a parent entity "domains" that contains an array of properly-formatted pattern.</p>

        <input type="hidden" ref="jsonType" value="domains">

        <div class="form-group">
            <label for="json-data">JSON</label>
            <textarea class="form-control" id="json-data" rows="12" v-model="jsonData"></textarea>
        </div>

        <button class="btn" id="create-from-json" v-on:click="createFromJson" :disabled="!jsonData">
            Process
        </button>
        @if (Auth::user())
            <input type="hidden" ref="apiToken" value="{{ Auth::user()->api_token }}">
        @endif
    </div>

    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</x-app-layout>

resources/views/domain/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Show Domain "{{ $domain->name }}"
        </h2>
    </x-slot>

    <div>
        <h1>Domain: {{ $domain->name }}</h1>

        <p><strong>Appearance Traits:</strong> {{ $domain->appearance_traits }}</p>
        <p><strong>Personality Traits:</strong> {{ $domain->personality_traits }}</p>
        <p><strong>Holy Items:</strong> {{ $domain->holy_items }}</p>
        <p><strong>Holy Symbols:</strong> {{ $domain->holy_symbols }}</p>

        @if (Auth::user()->is_admin)
            <p><a href="{{ route('domain.edit', ['domain' => $domain]) }}"
                  class="btn">Edit</a></p>
        @endif
    </div>
</x-app-layout>