routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('biome/json', 'BiomeController@json')->name('biome.json');
    Route::resource('biome', 'BiomeController');
    Route::get('charge/json', 'ChargeController@json')->name('charge.json');
    Route::post('charge/search', 'ChargeController@search')->name('charge.search');
    Route::resource('charge', 'ChargeController');
    Route::get('domain/json', 'DomainController@json')->name('domain.json');
    Route::resource('domain', 'DomainController');
    Route::get('mineral/json', 'MineralController@json')->name('mineral.json');
    Route::resource('mineral', 'MineralController');
    Route::get('pattern/json', 'PatternController@json')->name('pattern.json');
    Route::post('pattern/search', 'PatternController@search')->name('pattern.search');
    Route::resource('pattern', 'PatternController');
    Route::get('profession/json', 'ProfessionController@json')->name('profession.json');
    Route::resource('profession', 'ProfessionController');
    Route::get('resource/json', 'ResourceController@json')->name('resource.json');
    Route::post('resource/search', 'ResourceController@search')->name('resource.search');
    Route::resource('resource', 'ResourceController');
    Route::get('species/json', 'SpeciesController@json')->name('species.json');
    Route::get('species/quick', 'SpeciesController@quick')->name('species.quick');
    Route::post('species/search', 'SpeciesController@search')->name('species.search');
    Route::resource('species', 'SpeciesController');

    // Pattern routes
    Route::get('pattern/{pattern}/slot/create', 'PatternController@createSlot')->name('pattern.create_slot');
    Route::get('pattern/{pattern}/slot/{slot}/edit', 'PatternController@editSlot')->name('pattern.edit_slot');
    Route::post('pattern/{pattern}/slot', 'PatternController@storeSlot')->name('pattern.store_slot');
    Route::put('pattern/{pattern}/slot/{slot}', 'PatternController@updateSlot')->name('pattern.update_slot');

    // Species routes
    Route::get('species/{species}/resource/create', 'SpeciesController@createResource')->name('species.create_resource');
    Route::get('species/{species}/resource/{resource}/edit', 'SpeciesController@editResource')->name('species.edit_resource');
    Route::post('species/{species}/resource', 'SpeciesController@storeResource')->name('species.store_resource');
    Route::put('species/{species}/resource/{resource}', 'SpeciesController@updateResource')->name('species.update_resource');

    Route::get('species/{species}/age_category/create', 'SpeciesController@createAgeCategory')->name('species.create_age_category');
    Route::get('species/{species}/age_category/{age_category}/edit', 'SpeciesController@editAgeCategory')->name('species.edit_age_category');
    Route::post('species/{species}/age_category', 'SpeciesController@storeAgeCategory')->name('species.store_age_category');
    Route::put('species/{species}/age_category/{age_category}', 'SpeciesController@updateAgeCategory')->name('species.update_age_category');

    Route::get('species/{species}/trait_template/create', 'SpeciesController@createTraitTemplate')->name('species.create_trait_template');
    Route::get('species/{species}/trait_template/{trait_template}/edit', 'SpeciesController@editTraitTemplate')->name('species.edit_trait_template');
    Route::post('species/{species}/trait_template', 'SpeciesController@storeTraitTemplate')->name('species.store_trait_template');
    Route::put('species/{species}/trait_template/{trait_template}', 'SpeciesController@updateTraitTemplate')->name('species.update_trait_template');

    Route::post('quick/race', 'SpeciesController@storeQuickRace')->name('quick.race');

    // Mineral routes
    Route::get('mineral/{mineral}/resource/create', 'MineralController@createResource')->name('mineral.create_resource');
    Route::get('mineral/{mineral}/resource/{resource}/edit', 'MineralController@editResource')->name('mineral.edit_resource');
    Route::post('mineral/{mineral}/resource', 'MineralController@storeResource')->name('mineral.store_resource');
    Route::put('mineral/{mineral}/resource/{resource}', 'MineralController@updateResource')->name('mineral.update_resource');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'HomeController@index')->name('dashboard');

app/Models/Profession.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Profession extends Model
{
    protected $fillable = [
        'name',
        'description',
    ];

    protected $hidden = [
        'id',
        'created_at',
        'updated_at',
    ];

    public function patterns()
    {
        return $this->hasMany('App\Models\Pattern');
    }

    public function tags()
    {
        return $this->morphToMany('App\Models\Tag', 'taggable');
    }
}

app/Http/Controllers/ProfessionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Profession;
use App\Models\Tag;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProfessionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index()
    {
        $professions = Profession::orderBy('name')->paginate(15);

        return view('profession.index', ['professions' => $professions]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create()
    {
        return view('profession.create');
    }

    public function json()
    {
        return view('profession.json');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $profession = new Profession;

        $this->save($profession, $request);

        return redirect()->route('profession.show', ['profession' => $profession]);
    }

    /**
     * Display the specified resource.
     *
     * @param Profession $profession
     *
     * @return Renderable
     */
    public function show(Profession $profession)
    {
        return view('profession.show', ['profession' => $profession]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Profession $profession
     *
     * @return Renderable
     */
    public function edit(Profession $profession)
    {
        $tags = convert_tags_to_string($profession);

        return view('profession.edit', ['profession' => $profession, 'tags' => $tags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Profession $profession
     *
     * @return RedirectResponse
     */
    public function update(Request $request, Profession $profession)
    {
        $this->save($profession, $request);

        return redirect()->route('profession.show', ['profession' => $profession]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Profession $profession
     *
     * @return Response
     */
    public function destroy(Profession $profession)
    {
        //
    }

    function save(Profession $profession, Request $request)
    {
        $profession->name = $request->name;
        $profession->description = $request->description;

        $profession->save();

        update_tags($profession, $request->tags);
    }

    public function getJSON(Request $request)
    {
        if (!empty($request->query('tag'))) {
            $tag = Tag::where('name', '=', $request->query('tag'))->first();
            if (empty($tag)) {
                return response('{"professions": []}')->header('Content-Type', 'application/json');
            }
            $professions = $tag->professions()->with('tags')->get()->toJson();
        } else {
            $professions = Profession::with('tags')->get()->toJson();
        }

        $professions = '{"professions":' . $professions . '}';

        return response($professions)->header('Content-Type', 'application/json');
    }

    public function storeFromJson(Request $request)
    {
        $data = json_decode($request->data);

        if (empty($data->professions)) {
            return response('invalid data for professions', '400');
        }

        $newRecordsCount = 0;

        foreach ($data->professions as $object) {
            $profession = new Profession;

            $profession->name = $object->name;
            $profession->description = $object->description;

            $profession->save();

            if (sizeof($object->tags) > 0) {
                $tagArray = [];
                foreach ($object->tags as $tag) {
                    $tagArray [] = $tag->name;
                }
                $tags = implode(',', $tagArray);
                update_tags($profession, $tags);
            }

            $newRecordsCount++;
        }

        return response()->json([
            'state' => 'success',
            'new_records_count' => $newRecordsCount,
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/profession/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Profession
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="profession-creation-form" method="POST" action="{{ route('profession.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/profession/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Profession "{{ $profession->name }}"
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="profession-edit-form" method="POST"
              action="{{ route('profession.update', ['profession'=>$profession]) }}">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ $profession->name }}">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control"
                       value="{{ $profession->description }}">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control" value="{{ $tags }}">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/profession/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Professions
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        @if (Auth::user()->is_admin)
            <p class="flex">
                <a href="{{ route('profession.create') }}" class="btn">Create New</a>
                <a href="{{ route('profession.json') }}" class="btn">Create from JSON</a>
            </p>
        @endif

        <h2>List of Professions</h2>

        <table>
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($professions as $profession)
                <tr>
                    <td>
                        <a class="text-green-700 underline hover:no-underline" href="{{ route('profession.show', ['profession' => $profession]) }}">{{ $profession->name }}</a>
                    </td>
                    <td>{{ $profession->description }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $professions->links() }}
    </div>
</x-app-layout>

resources/views/profession/json.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Profession from JSON
        </h2>
    </x-slot>
    <div id="app">
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <p>@{{ message }}</p>

        <p>The JSON must have a parent entity "professions" that contains an array of properly-formatted pattern.</p>

        <input type="hidden" ref="jsonType" value="professions">

        <div class="form-group">
            <label for="json-data">JSON</label>
            <textarea class="form-control" id="json-data" rows="12" v-model="jsonData"></textarea>
        </div>

        <button class="btn" id="create-from-json" v-on:click="createFromJson" :disabled="!jsonData">
            Process
        </button>
        @if (Auth::user())
            <input type="hidden" ref="apiToken" value="{{ Auth::user()->api_token }}">
        @endif
    </div>

    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</x-app-layout>

resources/views/profession/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Profession: "{{ $profession->name }}"
        </h2>
    </x-slot>

    <div>
        <p>{{ $profession->description }}</p>

        <p><strong>Tags:</strong> @foreach($profession->tags as $tag)<span class="tag">{{$tag->name}}</span> @endforeach</p>

        @if (Auth::user()->is_admin)
            <p><a href="{{ route('profession.edit', ['profession'=>$profession]) }}"
                  class="btn">Edit</a></p>
        @endif
    </div>
</x-app-layout>