routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/', '/dashboard');

Route::middleware(['auth'])->group(function () {
    Route::get('biome/json', 'BiomeController@json')->name('biome.json');
    Route::resource('biome', 'BiomeController');
    Route::get('charge/json', 'ChargeController@json')->name('charge.json');
    Route::post('charge/search', 'ChargeController@search')->name('charge.search');
    Route::resource('charge', 'ChargeController');
    Route::get('domain/json', 'DomainController@json')->name('domain.json');
    Route::resource('domain', 'DomainController');
    Route::get('mineral/json', 'MineralController@json')->name('mineral.json');
    Route::resource('mineral', 'MineralController');
    Route::get('pattern/json', 'PatternController@json')->name('pattern.json');
    Route::post('pattern/search', 'PatternController@search')->name('pattern.search');
    Route::resource('pattern', 'PatternController');
    Route::get('profession/json', 'ProfessionController@json')->name('profession.json');
    Route::resource('profession', 'ProfessionController');
    Route::get('resource/json', 'ResourceController@json')->name('resource.json');
    Route::post('resource/search', 'ResourceController@search')->name('resource.search');
    Route::resource('resource', 'ResourceController');
    Route::get('species/json', 'SpeciesController@json')->name('species.json');
    Route::get('species/quick', 'SpeciesController@quick')->name('species.quick');
    Route::post('species/search', 'SpeciesController@search')->name('species.search');
    Route::resource('species', 'SpeciesController');

    // Pattern routes
    Route::get('pattern/{pattern}/slot/create', 'PatternController@createSlot')->name('pattern.create_slot');
    Route::get('pattern/{pattern}/slot/{slot}/edit', 'PatternController@editSlot')->name('pattern.edit_slot');
    Route::post('pattern/{pattern}/slot', 'PatternController@storeSlot')->name('pattern.store_slot');
    Route::put('pattern/{pattern}/slot/{slot}', 'PatternController@updateSlot')->name('pattern.update_slot');

    // Species routes
    Route::get('species/{species}/resource/create', 'SpeciesController@createResource')->name('species.create_resource');
    Route::get('species/{species}/resource/{resource}/edit', 'SpeciesController@editResource')->name('species.edit_resource');
    Route::post('species/{species}/resource', 'SpeciesController@storeResource')->name('species.store_resource');
    Route::put('species/{species}/resource/{resource}', 'SpeciesController@updateResource')->name('species.update_resource');

    Route::get('species/{species}/age_category/create', 'SpeciesController@createAgeCategory')->name('species.create_age_category');
    Route::get('species/{species}/age_category/{age_category}/edit', 'SpeciesController@editAgeCategory')->name('species.edit_age_category');
    Route::post('species/{species}/age_category', 'SpeciesController@storeAgeCategory')->name('species.store_age_category');
    Route::put('species/{species}/age_category/{age_category}', 'SpeciesController@updateAgeCategory')->name('species.update_age_category');

    Route::get('species/{species}/trait_template/create', 'SpeciesController@createTraitTemplate')->name('species.create_trait_template');
    Route::get('species/{species}/trait_template/{trait_template}/edit', 'SpeciesController@editTraitTemplate')->name('species.edit_trait_template');
    Route::post('species/{species}/trait_template', 'SpeciesController@storeTraitTemplate')->name('species.store_trait_template');
    Route::put('species/{species}/trait_template/{trait_template}', 'SpeciesController@updateTraitTemplate')->name('species.update_trait_template');

    Route::post('quick/race', 'SpeciesController@storeQuickRace')->name('quick.race');

    // Mineral routes
    Route::get('mineral/{mineral}/resource/create', 'MineralController@createResource')->name('mineral.create_resource');
    Route::get('mineral/{mineral}/resource/{resource}/edit', 'MineralController@editResource')->name('mineral.edit_resource');
    Route::post('mineral/{mineral}/resource', 'MineralController@storeResource')->name('mineral.store_resource');
    Route::put('mineral/{mineral}/resource/{resource}', 'MineralController@updateResource')->name('mineral.update_resource');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', 'HomeController@index')->name('dashboard');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/resource/create-for.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Resource for {{ $item->name }}
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="resource-creation-form" method="POST"
              action="{{ route($itemType . '.store_resource', [$itemType => $item]) }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control">
            </div>
            <div class="form-group">
                <label for="main_material">Main Material</label>
                <input type="text" id="main_material" name="main_material" class="form-control">
            </div>
            <div class="form-group">
                <label for="commonality">Commonality</label>
                <input type="number" id="commonality" name="commonality" class="form-control">
            </div>
            <div class="form-group">
                <label for="value">Value</label>
                <input type="number" id="value" name="value" class="form-control">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/resource/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Resource
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="resource-creation-form" method="POST" action="{{ route('resource.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control">
            </div>
            <div class="form-group">
                <label for="main_material">Main Material</label>
                <input type="text" id="main_material" name="main_material" class="form-control">
            </div>
            <div class="form-group">
                <label for="origin">Origin</label>
                <input type="text" id="origin" name="origin" class="form-control">
            </div>
            <div class="form-group">
                <label for="commonality">Commonality</label>
                <input type="number" id="commonality" name="commonality" class="form-control">
            </div>
            <div class="form-group">
                <label for="value">Value</label>
                <input type="number" id="value" name="value" class="form-control">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/resource/edit-for.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Resource "{{ $resource->name }}" for {{ $item->name }}
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="resource-edit-form" method="POST"
              action="{{ route($itemType . '.update_resource', [$itemType => $item, 'resource' => $resource]) }}">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ $resource->name }}">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control"
                       value="{{ $resource->description }}">
            </div>
            <div class="form-group">
                <label for="main_material">Main Material</label>
                <input type="text" id="main_material" name="main_material" class="form-control"
                       value="{{ $resource->main_material }}">
            </div>
            <div class="form-group">
                <label for="commonality">Commonality</label>
                <input type="number" id="commonality" name="commonality" class="form-control"
                       value="{{ $resource->commonality }}">
            </div>
            <div class="form-group">
                <label for="value">Value</label>
                <input type="number" id="value" name="value" class="form-control"
                       value="{{ $resource->value }}">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control" value="{{ $tags }}">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/resource/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Resource "{{ $resource->name }}"
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <form id="resource-edit-form" method="POST" action="{{ route('resource.update', ['resource' => $resource]) }}">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ $resource->name }}">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" id="description" name="description" class="form-control"
                       value="{{ $resource->description }}">
            </div>
            <div class="form-group">
                <label for="main_material">Main Material</label>
                <input type="text" id="main_material" name="main_material" class="form-control"
                       value="{{ $resource->main_material }}">
            </div>
            <div class="form-group">
                <label for="origin">Origin</label>
                <input type="text" id="origin" name="origin" class="form-control"
                       value="{{ $resource->origin }}">
            </div>
            <div class="form-group">
                <label for="commonality">Commonality</label>
                <input type="number" id="commonality" name="commonality" class="form-control"
                       value="{{ $resource->commonality }}">
            </div>
            <div class="form-group">
                <label for="value">Value</label>
                <input type="number" id="value" name="value" class="form-control"
                       value="{{ $resource->value }}">
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input id="tags" name="tags" type="text" class="form-control" value="{{ $tags }}">
            </div>
            <button type="submit" class="btn">Save</button>
        </form>
    </div>
</x-app-layout>

resources/views/resource/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Resources
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        @if (!empty($tag))
            <p>Showing only resources with tag "{{ $tag }}".</p>
        @endif

        @if (Auth::user()->is_admin)
            <p class="flex">
                <a href="{{ route('resource.create') }}" class="btn">Create New</a>
                <a href="{{ route('resource.json') }}" class="btn">Create from JSON</a>
            </p>
        @endif

        <form method="POST" action="{{ route('resource.search') }}">
            @csrf
            <div class="shadow flex m-4 items-center p-3">
                <h3 class="block mx-2 font-bold">Search</h3>
                <input type="text" name="name" class="border-3 border-gray-600 p-2"
                       placeholder="name to search for">
                <button type="submit" class="btn">Search</button>
            </div>
        </form>

        <h2>List of Resources</h2>

        <ul>
            @foreach ($resources as $resource)
                <li>
                    <a class="text-green-700 underline hover:no-underline" href="{{ route('resource.show', ['resource'=>$resource->id]) }}">{{ $resource->name }}</a>
                </li>
            @endforeach
        </ul>

        {{ $resources->links() }}
    </div>
</x-app-layout>

resources/views/resource/json.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Resource from JSON
        </h2>
    </x-slot>
    <div id="app">
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        <p>@{{ message }}</p>

        <p>The JSON must have a parent entity "resources" that contains an array of properly-formatted pattern.</p>

        <input type="hidden" ref="jsonType" value="resources">

        <div class="form-group">
            <label for="json-data">JSON</label>
            <textarea class="form-control" id="json-data" rows="12" v-model="jsonData"></textarea>
        </div>

        <button class="btn" id="create-from-json" v-on:click="createFromJson" :disabled="!jsonData">
            Process
        </button>
        @if (Auth::user())
            <input type="hidden" ref="apiToken" value="{{ Auth::user()->api_token }}">
        @endif
    </div>

    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</x-app-layout>

resources/views/resource/search.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Resource Search Results
        </h2>
    </x-slot>

    <div>
        @if (session('status'))
            <div class="alert" role="alert">
                {{ session('status') }}
            </div>
        @endif

        @if (!empty($tag))
            <p>Showing only resources with tag "{{ $tag }}".</p>
        @endif

        <form method="POST" action="{{ route('resource.search') }}">
            @csrf
            <div class="shadow flex m-4 items-center p-3">
                <h3 class="block mx-2 font-bold">Search</h3>
                <input type="text" name="name" class="border-3 border-gray-600 p-2"
                       placeholder="name to search for">
                <button type="submit" class="btn">Search</button>
            </div>
        </form>

        <h2>Search Results</h2>

        <ul>
            @foreach ($resources as $resource)
                <li>
                    <a class="text-green-700 underline hover:no-underline" href="{{ route('resource.show', ['resource'=>$resource->id]) }}">{{ $resource->name }}</a>
                </li>
            @endforeach
        </ul>

        {{ $resources->links() }}
    </div>
</x-app-layout>

resources/views/resource/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Resource "{{ $resource->name }}"
        </h2>
    </x-slot>

    <div>
        <p>{{ $resource->description }}</p>
        <p><strong>Main Material:</strong> {{ $resource->main_material }}</p>
        <p><strong>Origin:</strong> {{ $resource->origin }}</p>
        <p><strong>Commonality:</strong> {{ $resource->commonality }}</p>
        <p><strong>Value:</strong> {{ $resource->value }}</p>

        <p><strong>Tags:</strong> @foreach($resource->tags as $tag)<span class="tag">{{$tag->name}}</span> @endforeach</p>

        @if (Auth::user()->is_admin)
            <p><a href="{{ route('resource.edit', ['resource'=>$resource]) }}"
                  class="btn">Edit</a></p>
        @endif
    </div>
</x-app-layout>